version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    # Si tenés DB, agrega depends_on aquí.

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend